#!/system/bin/sh
[ "`whoami`" = "root" ] || ( su -c debian; exit)

DEBIAN=/data/local/mnt/Linux

mountpoint -q $DEBIAN/proc || mount -t proc proc $DEBIAN/proc
mountpoint -q $DEBIAN/dev || busybox mount --rbind /dev $DEBIAN/dev
mountpoint -q $DEBIAN/sys || busybox mount --rbind /sys $DEBIAN/sys
mountpoint -q $DEBIAN/mnt || busybox mount --rbind /storage $DEBIAN/mnt
mountpoint -q $DEBIAN/run || mount -t tmpfs -o rw,nosuid,mode=755 tmpfs $DEBIAN/run
[ -d $DEBIAN/run/user ] || mkdir $DEBIAN/run/user
mountpoint -q $DEBIAN/run/user || mount -t tmpfs -o rw,nosuid,nodev,noexec,size=102400k,mode=755 tmpfs $DEBIAN/run/user
[ -d $DEBIAN/run/lock ] || mkdir $DEBIAN/run/lock
mountpoint -q $DEBIAN/run/lock || mount -t tmpfs -o rw,nosuid,nodev,noexec,size=5120k tmpfs $DEBIAN/run/lock

export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
export LANG=zh_CN.UTF-8
export LANGUAGE=zh_CN:zh
export TERM=xterm
export HOME=/root
export SHELL=/bin/bash
if [[ -n "$*" ]] ; then
    /system/xbin/chroot $DEBIAN /bin/bash -c "$*"
else
    /system/xbin/chroot $DEBIAN /bin/bash
fi

export PATH=/sbin:/vendor/bin:/system/sbin:/system/bin:/system/xbin
unset LANG
unset LANGUAGE
export TERM=linux
export HOME=/
export SHELL=/system/bin/sh
