#!/bin/bash
case $1 in
0|1|2|3|4|5|6|S|s)
    mountpoint -q /run || ( echo '/run not mounted!'; exit 2)
    case $1 in
    s)
        S=S
    ;;
    *)
        S=$1
    ;;
    esac
    [ -f '/run/fakeinitctl' ] && [ `cat /run/fakeinitctl` = $S ] && exit 1
    for script in `ls /etc/rc$S.d`; do
        if [ ${script::1} = K ]; then
            /etc/rc$S.d/$script stop
        elif [ ${script::1} = S ]; then
            /etc/rc$S.d/$script start
        fi
    done
    echo $S > /run/fakeinitctl
;;
*)
    echo 'Usage: fakeinit {0|1|2|3|4|5|6|S|s}'
    exit 1
;;
esac
